# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=200)),
                ('eventLocation', models.CharField(max_length=200)),
                ('eventDate', models.DateTimeField(verbose_name='date published')),
                ('eventType', models.CharField(max_length=200)),
                ('eventDescription', models.CharField(max_length=2000)),
                ('eventLink', models.CharField(max_length=2000)),
            ],
        ),
    ]
